import 'dart:io';
import 'package:flutter/foundation.dart';
import 'globals.dart' as globals;

// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXNMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOxKWMMMMXO0WMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkd0WMMWOokO0O0XOONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOO0XXXOoclxkxdc::;;:cccoONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKXWMWNWMMWNX0Okkxo::clc:;:c:;;;;;:ooc:;:;:oodk0NWWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkokXKxodxdlclxkxxO0koccdoloc;;;;;cdl;;::cxOxdc:lollxXNX0KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOc:cc:,:ccxk0NMMMMMWN0xxdoOo;;:c::;;;clo0KkOKKKd:lccolcd0WMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkl:;,:::lx0WMWMMMMMMMMMWKxcc:;;;clc:cclxKWNXNMMWKdcclol::dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNockK0kxxk0NMMMMMMMMMMMMMMMN0kxollllccdkKWMMMMMMMMMNOdddoodclKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0ll0WMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOOKNWMMMMMMMMMMMMMWXXXNWXocxXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0oldXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOolxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKcoXMMMMMMMMMMMMMMMMMMMMMMMMMWNXXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd:OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWkcOMMMMMMMMMMMMMMWNXKXXXXKK000000OOKXXXXXXXNWWMMMMMMMMMMMMMMMMMMMMM0cxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXllXMMMMMMMMWNKK00K0OOO00O00KNWMMMNKOOOOO0O00KKKKKKKKK0KNWMMMMMMMMMMXocKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXoc0WMMMMMMMMMNKKXNNNNXXXK0KK000000KNWWWWWWWWWWWWNNNNNNNWWMMMMMMMMMMMMXoc0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXllKMMMMMMMMMMWX000KK000KK000000000OOO00KKKKKKKK000000O00KXXNMMMMMMMMMMMNocKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO:kWMMMMMMMMMMMWNNNWWWMMMMMMMMMMMWWNNNNNNNWWWWWWWWWNNK00000KNWMMMMMMMMMMM0cxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWdcKMMMMMMMMMMMMMMMMMMMMMMMWNX0OOOOO00000O00OKXNWWWWWWWWMMMMMMMMMMMMMMMMMMXcoNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXloNMMMMMMMMMMMWWNNNNNXK0O0000O0KXNWMMMMWWWNK0000KKKKKK00000000KWMMMMMMMMMNo:0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx:OWMMMMMMMMMMWXKKKKKK000KNWWMMMMMMMMMMMMMMMMMMWWWWWWWWWNNNNNNKKWMMMMMMMMMM0:oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO:dNMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMWNNNNXXNWMMMMMMMMMMMMMWkcOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk:OMMMMMMMMMMMWWNXXK0O000000O0NMMMMMMMMMMMMMMMMMMMMN0kOO0000OOkOO0KWMMMMMMMMM0ckMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx:OMMMMMMMWX0OOOOO00KKXXXXXXXKNMMMMMMMMMMMMMMMMMMWWNKXNWMMMMMWNXX0OkONWMMMMMM0cxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWdcKMMMMMMMN00XNWMMMMMMMMMMMMMWNNWMMMMMMMMMMMMMMWXO0WMMMMMMMMMMMMMMWXOOXWMMMMMXloNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNodNMMMMMMMMMMMMMMMMMMMMMMWWMMWKkONMMMMMMMMMMMMWKx0NWMMWWMMMMMWWWWWWWWWWMMMMMMNolXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdxWMMMMMMMWXKXXNNWWMMMMMMMMWWWWXO0WMMMMMMMMMMMWXXWWMMWWWWNX0koclooccxXWMMMMMMWdlXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKlkWMMMMMMMNk:;llc;:clodx0XWMMWWWNWWWWMMMMMMMMMWMMWW0xddl:,...  .lxc,kWMMMMMMMWxc0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKlkWMMMMMMMMNdlxkc.      .,cokKWWWWWWWMMMMMMMMMMMMNx:odd;        ;Od;kWMMMMMMMWdcKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNooXMMMMMMMMWKdloc.      ,oo:.;KMWWWMMMMMMMMMMWWMMXc;oxd,       .l0x:kWMMMMMMMXloNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWxcKMMMMMMMNkOXklc,.',;;:oo::cxXWWWWWWMMMMMMMMWWWWNx;'';:;'.....'cl:;dNMMMMMMMKcdWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0cdNMMMMMMNkll:;:,,clloollokXWWWWWWWWWWWMMMMWWWWWWNKxlooooodxkxc;:clkNMMMMMMXolKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOcxNXKNMMMWXOdc:odoolclloxKWWWWWWWNWWWMMMMMMMWWWWWNOooddlccodoc:lkXWMMMMMMNo:0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWxcxolKMMMMMMMWNNWWNNNNNNNWWMWWWW0d0MMMMMMMMMXx0WWWWXOxdoddkXXKKKNWMMMWNK0kcoNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk:ldoOO0NMMMMMMMMMMMMMMMMMMWWWWNxc0MMMMMMWWWKlxWWWWWWWWWWWWWWWMMMMMMMKoc:lclXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXocOxllldXMMMMMMMMMMMMMMWWWWWNXKd:dNMMMMMMWWMNd:OWWWWWWWWWWWWWWMMMMMMM0c::::;kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXlclldOdkWMMMMMMMMMMMMWWWNXKOxc;cxXMMMMMMMMWWWXdlxKNNNWWWWWWWWWWMMMMMWOlxo;;,kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo;:dOdl0Xk0WMMMMMMWWWNX0OOxoookXWMMMMMMMMMMWWWWKdokKXXXXXWWWWWWWWMMMXolOx:;,xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl;:lo::olckWMMMWWWWNK000XXkkXNWWMMMMMMMMMMMMMWMMW0dlxXNKOO0XWWWWWWWWOlllc:c:dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOc;;cc::::l0WWWWWNX0O0XNWWNko0WWWWWMMMMMMMMMMMMMWMW0:dNWWX0xd0NWWWWWXxxx:;:::xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:;;;:clllo0WWWNNKOOKNWWWWWKloXWWWWWWWWWWWWWWWWWWNk:lKWWWNNNOx0XNNWW0dxo;;,;xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOc;;:cc:lllkKKKKK0KNNXkxKNXKOdx0KXXKKXNNNNNNXKKXXOld0K0OO0XNX00XNXNNklc:c:,lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl;;;;;;::ccooododdol::oxooooclddolok0OOkxxxdooxdldxxxxlcx0Oxxxdoxkc:;:lclddkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk:;;;;;;;:lddllcc::cll:cxOkxxxkkxxxxkkkkxoddxxddodoc::lccoc:lcll::;;;;,;loo0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd:;;;:::okxolccl::cxOo;oXNNNNNNWWNNNNNNNXXNNXK0Okd;,lO0kkddocxx:;;::;:dxlkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd;;::::odc:llcc:loldlcoxKWMMMMMMMWWWWWMWWMWWWWWXOdxKOOXK0xc:dxlcll:;:odkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd:::;,;::;:ccc::lcc:;lkkddOXNWMMMMWWMMMMMMMWNXKOO0XXxclclc;::ccc:;;cdx0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOlcc:;,,;;;;;cl:;;:c:cld0klldk00KKKKXNNNXKK0OkO0O0XN0l;::::::;;;;;;;oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0XKK0o;;:cc:ll;:::::ldoxo:dKK00OOkkkOO00000KXXNNNXOo:;:;;;;;;;;;;;cOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk;;cc;:oc:ll;clcc::cldkx000XNNNNXK0kOXNKx0XOlll:;;;;;;:;;;,;;cd0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWkccc:ccc:;:;:dkc;;colcccdod0KX0kkxkdlO0o:dx::::;;;::;:::;;;;:::o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOcdKd::c:;;:;:ll:;cc:::co0x::cdxkO0ko:cc;;c:;;;:;;;:;;;;;;::;d0KKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXloNWKkddoc:;;;:cccol:dOdoxc;;lxxdooko:;cc:;;;;:c:;;;;:oo:;oOllKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkcOMMMMWWNKo:;,;lc:oxodd:::;:::;;;:cdo:;ll:;;;;cl:;;;;l0KdxXWKldNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd:0MMMMMMMNxccll:,:ddc::;;;;;:oo:;looo:;c:;;cc:ll;:lc:dXWWWMMWdcKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkcdNMMMMMMMWX0XNXkl;;;lolc:::cx0kc;:c::::c:cdko;;;;:ldkNMMMMMMWx:OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd,dNMMMMMMMMMMMMWWWKo::ccccc::col:;;;;;:c;:::c:;:ldoldKWMMMMMMMMXocOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo:xNMMMMMMMMMWXOOOKWWXOkkkkddddlc::clc::lddc;:odx0NWXKWMMMMMMMMMMMNo;kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd:kWMMMMMMMMWKkk0XWWMMMMMMMMWWWWXK00KXOdkXWNOd0NWWMMXOXMMMMMMMMMMMMMNd:xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd;dNMMMMMMMMMKdkWMMMMMMMMMMMMMMMWWWWMWWXKNWWWWWWMMMMMNxkWMMMMMMMMMMMMMNl:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM


Future<void> coomCheck() async {
  try {
    final coomerLookup = await InternetAddress.lookup('pornhub.com');
    if (coomerLookup.isNotEmpty && coomerLookup[0].rawAddress.isNotEmpty) {
      bool coomDenied = false;
      for (var element in coomerLookup) {
        // If the returned ip address is anything but the Cisco Content Category Block Page
        // then the private DNS settings has not been set with FamilyShield OpenDNS
        // https://support.opendns.com/hc/en-us/articles/227986927-What-are-the-Cisco-Umbrella-Block-Page-IP-Addresses-
        if (element.rawAddress[0] != 146) {
          continue;
        } else if (element.rawAddress[1] != 112) {
          continue;
        } else if (element.rawAddress[2] != 61) {
          continue;
        } else if (element.rawAddress[3] != 106) {
          continue;
        }

        coomDenied = true;
        break;
      }

      if (kDebugMode) {
        print('coomDenied = ${coomDenied}');
      }

      globals.coomCheckPassed = coomDenied;
      return;
    }
  } on SocketException catch (_) {

    if (kDebugMode) {
      print('not connected');
    }

    globals.coomCheckPassed = true;

    return;
  }

  globals.coomCheckPassed = false;
}